/*
BSD local Magma p=3 remaining cases
Generated by bsd_local_magma_batch_export.py.
Run locally with Magma.  This file intentionally does not call SetClassGroupBounds("GRH"); p=3 output is intended to be unconditional.
*/

SetColumns(0);

print "===== 2429b1 p=3 unconditional =====";
print "label=2429b1 conductor=2429 target=9 expectedSelmer=9";
E := EllipticCurve([1, 1, 0, -115, -528]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);
print "ThreeSelmerGroup";
try
    G, phi := ThreeSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "ThreeSelmerGroup ERROR";
    print err`Object;
end try;
print "===== END 2429b1 =====";
print "===== 2534e1 p=3 unconditional =====";
print "label=2534e1 conductor=2534 target=9 expectedSelmer=9";
E := EllipticCurve([1, -1, 1, -1393324, -640018129]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);
print "ThreeSelmerGroup";
try
    G, phi := ThreeSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "ThreeSelmerGroup ERROR";
    print err`Object;
end try;
print "===== END 2534e1 =====";
print "===== 2534f1 p=3 unconditional =====";
print "label=2534f1 conductor=2534 target=9 expectedSelmer=9";
E := EllipticCurve([1, -1, 1, -303, -1955]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);
print "ThreeSelmerGroup";
try
    G, phi := ThreeSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "ThreeSelmerGroup ERROR";
    print err`Object;
end try;
print "===== END 2534f1 =====";
print "===== 2674b1 p=3 unconditional =====";
print "label=2674b1 conductor=2674 target=9 expectedSelmer=9";
E := EllipticCurve([1, 1, 0, -2758, -55020]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);
print "ThreeSelmerGroup";
try
    G, phi := ThreeSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "ThreeSelmerGroup ERROR";
    print err`Object;
end try;
print "===== END 2674b1 =====";
print "===== 2849a1 p=3 unconditional =====";
print "label=2849a1 conductor=2849 target=9 expectedSelmer=9";
E := EllipticCurve([1, 1, 1, -53484, -4843180]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);
print "ThreeSelmerGroup";
try
    G, phi := ThreeSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "ThreeSelmerGroup ERROR";
    print err`Object;
end try;
print "===== END 2849a1 =====";
