/*
BSD local Magma p=5 intrinsic probes
Generated by bsd_local_magma_batch_export.py.
Run locally with Magma.  This file probes whichever p=5 Selmer intrinsics your local Magma exposes.
*/

SetColumns(0);

print "===== 1664k1 p=5 probe =====";
print "label=1664k1 conductor=1664 target=25 expectedSelmer=25";
E := EllipticCurve([0, -1, 0, -76162, -8064798]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);

print "FiveSelmerGroup";
try
    G, phi := FiveSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "FiveSelmerGroup ERROR";
    print err`Object;
end try;

print "SelmerGroup_5_E";
try
    G5 := SelmerGroup(5, E);
    print G5;
catch err
    print "SelmerGroup(5,E) ERROR";
    print err`Object;
end try;

print "SelmerGroup_E_5";
try
    H5 := SelmerGroup(E, 5);
    print H5;
catch err
    print "SelmerGroup(E,5) ERROR";
    print err`Object;
end try;
print "===== END 1664k1 =====";
print "===== 2366f1 p=5 probe =====";
print "label=2366f1 conductor=2366 target=25 expectedSelmer=25";
E := EllipticCurve([1, -1, 0, -528241, -147664867]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);

print "FiveSelmerGroup";
try
    G, phi := FiveSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "FiveSelmerGroup ERROR";
    print err`Object;
end try;

print "SelmerGroup_5_E";
try
    G5 := SelmerGroup(5, E);
    print G5;
catch err
    print "SelmerGroup(5,E) ERROR";
    print err`Object;
end try;

print "SelmerGroup_E_5";
try
    H5 := SelmerGroup(E, 5);
    print H5;
catch err
    print "SelmerGroup(E,5) ERROR";
    print err`Object;
end try;
print "===== END 2366f1 =====";
print "===== 2574d1 p=5 probe =====";
print "label=2574d1 conductor=2574 target=25 expectedSelmer=25";
E := EllipticCurve([1, -1, 0, -51969609, -144342625779]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);

print "FiveSelmerGroup";
try
    G, phi := FiveSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "FiveSelmerGroup ERROR";
    print err`Object;
end try;

print "SelmerGroup_5_E";
try
    G5 := SelmerGroup(5, E);
    print G5;
catch err
    print "SelmerGroup(5,E) ERROR";
    print err`Object;
end try;

print "SelmerGroup_E_5";
try
    H5 := SelmerGroup(E, 5);
    print H5;
catch err
    print "SelmerGroup(E,5) ERROR";
    print err`Object;
end try;
print "===== END 2574d1 =====";
print "===== 2834d1 p=5 probe =====";
print "label=2834d1 conductor=2834 target=25 expectedSelmer=25";
E := EllipticCurve([1, -1, 1, -8109, -279017]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);

print "FiveSelmerGroup";
try
    G, phi := FiveSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "FiveSelmerGroup ERROR";
    print err`Object;
end try;

print "SelmerGroup_5_E";
try
    G5 := SelmerGroup(5, E);
    print G5;
catch err
    print "SelmerGroup(5,E) ERROR";
    print err`Object;
end try;

print "SelmerGroup_E_5";
try
    H5 := SelmerGroup(E, 5);
    print H5;
catch err
    print "SelmerGroup(E,5) ERROR";
    print err`Object;
end try;
print "===== END 2834d1 =====";
print "===== 2900d1 p=5 probe =====";
print "label=2900d1 conductor=2900 target=25 expectedSelmer=25";
E := EllipticCurve([0, 0, 0, -120775, -16155250]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);

print "FiveSelmerGroup";
try
    G, phi := FiveSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "FiveSelmerGroup ERROR";
    print err`Object;
end try;

print "SelmerGroup_5_E";
try
    G5 := SelmerGroup(5, E);
    print G5;
catch err
    print "SelmerGroup(5,E) ERROR";
    print err`Object;
end try;

print "SelmerGroup_E_5";
try
    H5 := SelmerGroup(E, 5);
    print H5;
catch err
    print "SelmerGroup(E,5) ERROR";
    print err`Object;
end try;
print "===== END 2900d1 =====";
