"""Export local Magma batch probes for BSD descent cases."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


P3_OUT = "bsd_local_magma_p3_remaining.m"
P5_OUT = "bsd_local_magma_p5_probe.m"
README_OUT = "bsd_local_magma_readme.md"


@dataclass(frozen=True)
class DescentCase:
    label: str
    conductor: int
    a_invariants: list[int]
    prime: int
    target_primary_order: int
    expected_selmer_order: int
    predicted_sha_order: int
    predicted_sha_factorization: str
    torsion_primary_order: int | None = None

    @property
    def coeffs(self) -> str:
        return ", ".join(str(value) for value in self.a_invariants)


P3_REMAINING_CASES = [
    DescentCase("2429b1", 2429, [1, 1, 0, -115, -528], 3, 9, 9, 9, "3^2"),
    DescentCase("2534e1", 2534, [1, -1, 1, -1393324, -640018129], 3, 9, 9, 9, "3^2"),
    DescentCase("2534f1", 2534, [1, -1, 1, -303, -1955], 3, 9, 9, 9, "3^2"),
    DescentCase("2674b1", 2674, [1, 1, 0, -2758, -55020], 3, 9, 9, 9, "3^2"),
    DescentCase("2849a1", 2849, [1, 1, 1, -53484, -4843180], 3, 9, 9, 9, "3^2"),
]


P5_PROBE_CASES = [
    DescentCase("1664k1", 1664, [0, -1, 0, -76162, -8064798], 5, 25, 25, 25, "5^2", 1),
    DescentCase("2366f1", 2366, [1, -1, 0, -528241, -147664867], 5, 25, 25, 25, "5^2", 1),
    DescentCase("2574d1", 2574, [1, -1, 0, -51969609, -144342625779], 5, 25, 25, 25, "5^2", 1),
    DescentCase("2834d1", 2834, [1, -1, 1, -8109, -279017], 5, 25, 25, 25, "5^2", 1),
    DescentCase("2900d1", 2900, [0, 0, 0, -120775, -16155250], 5, 25, 25, 25, "5^2", 1),
]


def _case_from_row(row: dict) -> DescentCase:
    return DescentCase(
        label=row["label"],
        conductor=int(row["conductor"]),
        a_invariants=[int(value) for value in row.get("aInvariants", row.get("weierstrass", []))],
        prime=int(row["prime"]),
        target_primary_order=int(row["targetPrimaryOrder"]),
        expected_selmer_order=int(row["expectedSelmerOrder"]),
        predicted_sha_order=int(row.get("predictedShaOrder", row.get("targetPrimaryOrder", 0))),
        predicted_sha_factorization=str(row.get("predictedShaFactorization", "")),
        torsion_primary_order=(
            int(row["torsionPrimaryOrder"])
            if row.get("torsionPrimaryOrder") is not None
            else None
        ),
    )


def load_p3_cases(path: Path | None) -> list[DescentCase]:
    if path is None:
        return list(P3_REMAINING_CASES)
    data = json.loads(path.read_text())
    rows = data.get("selectedThreeSelmerTasks") or data.get("threeSelmerTasks") or data.get("curves") or []
    return [_case_from_row({**row, "prime": row.get("prime", 3)}) for row in rows if int(row.get("prime", 3)) == 3]


def load_p5_cases(path: Path | None) -> list[DescentCase]:
    if path is None:
        return list(P5_PROBE_CASES)
    data = json.loads(path.read_text())
    rows = data.get("tasks") or data.get("externalDescentTasks") or data.get("curves") or []
    cases = []
    for row in rows:
        prime = int(row.get("prime", 5))
        if prime != 5:
            continue
        cases.append(_case_from_row({**row, "prime": prime}))
    return cases


def magma_header(title: str, note: str) -> str:
    return f'''/*
{title}
Generated by bsd_local_magma_batch_export.py.
Run locally with Magma.  {note}
*/

SetColumns(0);
'''


def p3_case_code(case: DescentCase) -> str:
    return f'''print "===== {case.label} p=3 unconditional =====";
print "label={case.label} conductor={case.conductor} target={case.target_primary_order} expectedSelmer={case.expected_selmer_order}";
E := EllipticCurve([{case.coeffs}]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);
print "ThreeSelmerGroup";
try
    G, phi := ThreeSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "ThreeSelmerGroup ERROR";
    print err`Object;
end try;
print "===== END {case.label} =====";
'''


def p5_case_code(case: DescentCase) -> str:
    return f'''print "===== {case.label} p=5 probe =====";
print "label={case.label} conductor={case.conductor} target={case.target_primary_order} expectedSelmer={case.expected_selmer_order}";
E := EllipticCurve([{case.coeffs}]);
print "RankBound";
print RankBound(E);
print "Torsion";
T := TorsionSubgroup(E);
print T;
print Order(T);

print "FiveSelmerGroup";
try
    G, phi := FiveSelmerGroup(E);
    print G;
    print Order(G);
    if Order(G) gt 1 then
        print "Generators";
        for g in Generators(G) do
            print g;
            print Order(g);
            print phi(g);
        end for;
    end if;
catch err
    print "FiveSelmerGroup ERROR";
    print err`Object;
end try;

print "SelmerGroup_5_E";
try
    G5 := SelmerGroup(5, E);
    print G5;
catch err
    print "SelmerGroup(5,E) ERROR";
    print err`Object;
end try;

print "SelmerGroup_E_5";
try
    H5 := SelmerGroup(E, 5);
    print H5;
catch err
    print "SelmerGroup(E,5) ERROR";
    print err`Object;
end try;
print "===== END {case.label} =====";
'''


def render_p3_magma(cases: list[DescentCase]) -> str:
    body = "\n".join(p3_case_code(case).rstrip() for case in cases)
    note = (
        'This file intentionally does not call SetClassGroupBounds("GRH"); '
        "p=3 output is intended to be unconditional."
    )
    return magma_header("BSD local Magma p=3 remaining cases", note) + "\n" + body + "\n"


def render_p5_magma(cases: list[DescentCase]) -> str:
    body = "\n".join(p5_case_code(case).rstrip() for case in cases)
    note = "This file probes whichever p=5 Selmer intrinsics your local Magma exposes."
    return magma_header("BSD local Magma p=5 intrinsic probes", note) + "\n" + body + "\n"


def render_readme(p3_cases: list[DescentCase], p5_cases: list[DescentCase]) -> str:
    p3_rows = "\n".join(
        f"| `{case.label}` | {case.conductor} | `{case.a_invariants}` | {case.expected_selmer_order} |"
        for case in p3_cases
    )
    p5_rows = "\n".join(
        f"| `{case.label}` | {case.conductor} | `{case.a_invariants}` | {case.expected_selmer_order} |"
        for case in p5_cases
    )
    p3_recorders = "\n".join(
        f"python3 /Users/mbf_mini/p3/codex-2/bsd_record_magma_three_selmer.py --label {case.label} --raw-file transcripts/magma_{case.label}_three_selmer.txt"
        for case in p3_cases
    )
    p5_json = "\n".join(
        f'  {{"label":"{case.label}","weierstrass":{case.a_invariants},"prime":5,"expectedFiveSelmerOrder":{case.expected_selmer_order},"fiveSelmerTranscript":"transcripts/magma_{case.label}_five_probe.txt"}},'
        for case in p5_cases
    ).rstrip(",")
    return f"""# BSD Local Magma Batch Export

This export contains local Magma scripts for the remaining BSD primary-descent
checks.  The p=3 batch is intended to be unconditional and deliberately does
not enable `SetClassGroupBounds("GRH")`.

## Files

- `{P3_OUT}`: all {len(p3_cases)} remaining p=3 cases, unconditional.
- `{P5_OUT}`: all {len(p5_cases)} p=5 cases with `FiveSelmerGroup` and generic intrinsic probes.
- `{README_OUT}`: this command and transcript guide.

## Run Commands

```bash
magma -b {P3_OUT} | tee bsd_local_magma_p3_remaining.out
magma -b {P5_OUT} | tee bsd_local_magma_p5_probe.out
```

If your local Magma does not use `-b`, run:

```bash
magma {P3_OUT} | tee bsd_local_magma_p3_remaining.out
magma {P5_OUT} | tee bsd_local_magma_p5_probe.out
```

## p=3 Expected Output

Each p=3 block should print a `ThreeSelmerGroup` section.  Expected success is
`Order(G) = 9` for every row below.

| label | conductor | a-invariants | expected `Order(G)` |
|---|---:|---|---:|
{p3_rows}

If a p=3 case times out, save the partial output and rerun that single block
locally with more time.  Do not mark it confirmed from a GRH-only transcript.

## p=5 Expected Output

Each p=5 block probes three possible intrinsics:

1. `FiveSelmerGroup(E)`
2. `SelmerGroup(5, E)`
3. `SelmerGroup(E, 5)`

Expected successful 5-primary evidence, if your Magma exposes it, is an order
`25` group or an explicit `Z/5 + Z/5`-type structure.  If all intrinsics report
errors, keep the transcript as an intrinsic-availability probe, not as a
certificate.

| label | conductor | a-invariants | target order |
|---|---:|---|---:|
{p5_rows}

## Split Transcripts

The scripts print headers of the form:

```text
===== LABEL p=3 unconditional =====
...
===== END LABEL =====
```

and:

```text
===== LABEL p=5 probe =====
...
===== END LABEL =====
```

Save each block to:

- `transcripts/magma_LABEL_three_selmer.txt`
- `transcripts/magma_LABEL_five_probe.txt`

## Feed p=3 Transcripts Back Into Recorders

Legacy catalog recorder commands:

```bash
{p3_recorders}
```

For OpenDescent JSON certificates, add per curve:

```json
{{
  "threeSelmerTranscript": "transcripts/magma_LABEL_three_selmer.txt",
  "expectedSelmerOrder": 9,
  "prime": 3
}}
```

Then run:

```bash
python3 -m opendescent.cli input.json --backend native --evidence-transcripts --summary-only
```

## Feed p=5 Probe Transcripts Back Into OpenDescent

If a p=5 transcript contains a real group/order result, add records like:

```json
{{
  "curves": [
{p5_json}
  ]
}}
```

Then run:

```bash
python3 -m opendescent.cli input.json --backend native --evidence-transcripts --summary-only
```

If the p=5 transcript only contains intrinsic errors, keep it as raw probe
evidence and do not claim `fiveSelmerEvidence.status=selmer_group_match`.
"""


def export_batches(out_dir: Path, p3_cases: list[DescentCase], p5_cases: list[DescentCase]) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    outputs = {
        P3_OUT: out_dir / P3_OUT,
        P5_OUT: out_dir / P5_OUT,
        README_OUT: out_dir / README_OUT,
    }
    outputs[P3_OUT].write_text(render_p3_magma(p3_cases))
    outputs[P5_OUT].write_text(render_p5_magma(p5_cases))
    outputs[README_OUT].write_text(render_readme(p3_cases, p5_cases))
    return outputs


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Export local Magma batches for OpenDescent BSD cases.")
    parser.add_argument("--out-dir", default=".", help="Directory for generated Magma/readme files.")
    parser.add_argument("--p3-json", help="Optional bsd_primary_descent_tasks.json source.")
    parser.add_argument("--p5-json", help="Optional bsd_5primary_probe.json source.")
    args = parser.parse_args(argv)

    p3_cases = load_p3_cases(Path(args.p3_json) if args.p3_json else None)
    p5_cases = load_p5_cases(Path(args.p5_json) if args.p5_json else None)
    outputs = export_batches(Path(args.out_dir), p3_cases, p5_cases)
    for name, path in outputs.items():
        print(f"wrote {name}: {path}")
    print(f"p=3 cases: {len(p3_cases)}")
    print(f"p=5 cases: {len(p5_cases)}")


if __name__ == "__main__":
    main()
